name: Generate Sitemap

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          sitemap-format: xml
          base-url-path: http://spl3vrmh.dpdns.org
          include-html: true
          include-pdf: false

      - name: Commit and Push Sitemap
        run: |
          if ! git diff --quiet sitemap.xml; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add sitemap.xml
            git commit -m "Automated sitemap update"
            git push
          fi
